config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users

  resources :lines, except: [:new] do
    resource :favorites, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]

    resources :stories, only: [:show, :create, :edit, :update]
      #resources :comments, only: [:create, :destroy]

  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :line
  belongs_to :user

  validates :line_comment, presence: true, length: {maximum: 100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :line

  validates_uniqueness_of :line_id, scope: :user_id
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stories, dependent: :destroy

  enum jenru:{ミステリー:0, 青春:1, 恋愛:2, SF:3,ファンタジー:4, ホラー:5, コメディ:6, 経済:7, その他:8}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :content, presence: true, uniqueness: true, length: {minimum: 2, maximum: 200}
  validates :book_title, presence: true, uniqueness: true, length: {maximum: 20}
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :line
  belongs_to :user

  validates :story_comment, presence: true, length: {minimum: 2, maximum: 200}

  def parent_story(resource_id)
    Story.find(resource_id)
  end

  def all_parents(parents = [], resource_id)
    pp parent = parent_story(resource_id)

    if parent.story_id.nil?
      #pp "True"
      parents << parent
      #parents << parent.line.content
    else
      #pp "False"
      parents << parent
      all_parents(parents, parent.story_id)
    end
  end

  def child_story(resource_id)
    Story.find(story_id: resource_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lines, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stories, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :introduction])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @line = Line.find(params[:line_id])
    @comment = current_user.comments.new(comment_params)
    @comment.line_id = @line.id
    if @comment.save
      redirect_to request.referer
    else
      #@comments = Comment.all
      @new_story = Story.new
      @stories = @line.stories
      @first_stories = @stories.where(story_id: nil)
      render template: "lines/show"
      #render line_path(@line.id)うまくいかなかった
    end
  end
  
  def destroy
    line = Line.find(params[:line_id])
    comment = Comment.find_by(id: params[:id], line_id: params[:line_id])
    if comment.user_id == current_user.id
      comment.destroy
      redirect_to request.referer
    end
  end
  
  protected
  def comment_params
    params.require(:comment).permit(:line_comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    line = Line.find(params[:line_id])
    favorite = current_user.favorites.new(line_id: line.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    line = Line.find(params[:line_id])
    favorite = current_user.favorites.find_by(line_id: line.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
before_action :set_params, only: [:show, :edit, :update, :destroy]

  def create
    @line = Line.new(line_params)
    @line.user_id = current_user.id
    if @line.save
      redirect_to lines_path, notice: "Line is created successfully!"
    else
      @lines = Line.all
      render :index
    end
  end

  def index
    @lines = Line.all
    @line = Line.new()
  end

  def show
    @comment = Comment.new()
    #@comments = Comment.all
    @new_story = Story.new
    @stories = @line.stories
    @first_stories = @stories.where(story_id: nil)
  end

  def edit
  end

  def update
    if @line.update(line_params)
      redirect_to lines_path, notice: "Line is updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    if @line.destroy
      redirect_to lines_path
    else
      render :edit
    end
  end

  protected
  def line_params
    params.require(:line).permit(:content, :book_title)
  end

  def set_params
    @line = Line.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def show
    #@story = Story.find(params[:id])
    #@parent_story = Story.find_by(story_id: params[:story_id])
    #@stories = Story.where(story_id: @story.id)
    @new_story = Story.new
    @line = Line.find(params[:line_id])
    @story = Story.find_by(line_id: @line.id, id: params[:id])
    @stories = Story.where(story_id: @story.id)
  end

  def create
    @line = Line.find(params[:line_id])
    @new_story = @line.stories.new(story_params)
    #story._new.html.erbでhiddenを使いstory_idを送っているはず
    if @new_story.save
      redirect_to request.referer, notice: "Story is created successfully!"
    else
      @story = Story.find_by(line_id: @line.id, id: story_params[:story_id])
      if @new_story.story_id #2つ目以降のstory
        #if Story.where(story_id: @story.id)
          @stories = Story.where(story_id: @story.id)
        #else
        #  @stories = @line.stories.where.not(id: nil)
        #end
        render :show
      else #１つ目のstory
        @stories = @line.stories
        @first_stories = @stories.where(story_id: nil)
        @comment = Comment.new()
        render  template: 'lines/show'
      end
    end
  end

  def edit
    @line = Line.find(params[:line_id])
    @story = Story.find_by(line_id: @line.id, id: params[:id])
  end

  def update
    @line = Line.find(params[:line_id])
    @story = Story.find_by(line_id: @line.id, id: params[:id])
    if @story.update(update_params)
      redirect_to line_story_path(@line, @story), notice: "Story is updated successfully!"
    else
      render :edit
    end
  end

  def destroy #これをするならdependent: :destroyを考えないといけない
  end

  protected
  def story_params
    params.require(:story).permit(:user_id, :story_id, :story_comment)
    #params.require(:story).permit(:story_comment, :line_id).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:story).permit(:story_comment)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_params

  def show
    @lines = @user.lines.all
  end

  def edit
    if @user.id == current_user.id
      render :edit
    else
      redirect_to request.referer
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  protected
  def user_params
    params.require(:user).permit(:name, :introduction)
  end

  def find_params
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/middles_helper.rb
module MiddlesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lines/_first_story.html.erb
<%=form_with(model: [line, Story.new], local:true) do |f| %>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= f.label :story_comment %>
    <%= f.text_area :story_comment, autofocus:true, autocomplete: "story_comment", class:"form-control"%>
  </div>

  <div class="action">
    <%= f.submit "create story", class:"btn btn-success"%>
  </div>
<% end %>

app/views/lines/_new_line.html.erb
<%= form_with model:line, url: lines_path(line), method: :post,local:true do |f| %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, autofocus:true, class:"form-control"%>
  </div>

  <div class="field">
    <%= f.label :book_title %><br />
    <%= f.text_field :book_title, autofocus:true, autocomplete: "book_title" %>
  </div>

  <div class="field">
    <%= f.label :jenru %><br />
    <%= select :jenrus,:name,Line.jenrus.keys.to_a %>
  </div>

  <div class="action">
    <%= f.submit "create", class:"btn btn-success" %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>書き出し文　編集</h1>

<%= form_with model:@line, url: line_path, method: :patch, local:true do |f| %>

<div class="field">
  <%= f.label :content %><br />
  <%= f.text_field :content, autofocus:true %>
</div>

<div class="field">
  <%= f.label :book_title %><br />
  <%= f.text_field :book_title, autofocus:true, autocomplete: "book_title" %>
</div>

<div class="action">
  <%= f.submit "update" %>
</div>
<% end %>

app/views/lines/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1 class="my-5">書き出し文一覧</h1>
      <% @lines.each do |line| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-text"><%= link_to line.content, line_path(line.id) %></h5>
            <p class="card-text"><%= line.book_title %></p>
            <a class="card-text"><%= link_to line.user.name, user_path(line.user_id) %></a>
            <a>
              <% if line.favorited_by?(current_user) %>
                <%= link_to line_favorites_path(line), method: :delete do %>
                  <i class="fas fa-heart"></i><%= line.favorites.count%>
                <% end %>
              <% else %>
                <%= link_to line_favorites_path(line), method: :post do %>
                  <i class="far fa-heart"></i><%= line.favorites.count%>
                <% end %>
              <% end %>
            </a>
        　 </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-3 offset-md-1 my-2">
      <h3>新しい書き出し文を作る</h3>
      <%= render "layouts/error", obj:@line %>
      <%= render "lines/new_line", line:@line %>
    </div>

  </div>
</div>

app/views/lines/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 my-3">
      <h1>この書き出し文の詳細</h1>

      <div class="card">
          <div class="card-body">
            <h5 class="card-text"><%= @line.content %></h5>
            <div class="card-text ">
              タイトル：<i><%= @line.book_title %></i>
              ジャンル：<i><%= @line.jenru %></i>
              ユーザー:<i><%= link_to @line.user.name, user_path(@line.user_id) %></i>
            </div>
            <a>
              <% if @line.favorited_by?(current_user) %>
                <%= link_to line_favorites_path(@line), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @line.favorites.count%>
                <% end %>
              <% else %>
                <%= link_to line_favorites_path(@line), method: :post do %>
                  <i class="far fa-heart"></i><%= @line.favorites.count%>
                <% end %>
              <% end %>
            </a>
            <p class="card-text">
              <% if @line.user_id == current_user.id %>
                <%= link_to "Edit", edit_line_path(@line) %>
                <%= link_to "destroy", line_path(@line), method: :delete, data: {confirm: "削除しますか？"} %>
            <% end %>
            </p>
          </div>
      </div>

    <%= render "layouts/error", obj:@new_story %>
    <%= render "lines/first_story", line:@line, class:"my-4" %>

      <div class="col-md-12 mx-auto">
        <h5 class="mt-4">story(この書き出しの続き)一覧</h5>
            <div class="row">
              <% @first_stories.each do |story| %>
                <div class="card col-6">
                  <div class="card-body">
                    <p class="card-text"><%= link_to story.story_comment, line_story_path(@line.id, story.id) %></p>
                    <p class="card-text"><%= story.user.name %></p>
                  </div>
                </div>
              <% end %>
            </div>
      </div>
    </div>

    <div class="col-md-3 offset-md-1 my-5">
    <h5>この書き出し文に対するコメント一覧</h5>
      <table class="table">
        <tbody>
          <% @line.comments.each do |comment| %>
            <tr>
              <td>
                <p><%= comment.line_comment %></p>
              </td>
              <td>
                <p><%= link_to comment.user.name, user_path(comment.user) %></p>
              </td>
              <td>
                <% if comment.user.id == current_user.id %>
                  <%= link_to "Destroy", line_comment_path(@line.id, comment.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= render "layouts/error", obj:@comment %>
    <%=form_with model:[@line, @comment], url: line_comments_path(@line.id), method: :post,local:true do |f| %>
      <div class="field">
        <%= f.label :line_comment %>
        <%= f.text_area :line_comment, autofocus:true, autocomplete: "line_comment", class:"form-control"%>
      </div>

      <div class="action">
        <%= f.submit "create comment", class:"btn btn-success"%>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/stories/_until_story.html.erb
<nav id="navbar-example2" class="navbar navbar-light bg light">
  <a class="navbar-brand" href="#">Navbar</a>
</nav>
<div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
  <% if story.story_id.present? %>
      <p><%= link_to story.line.content, line_path(story.line_id) %></p>
      <% story.all_parents(@story.story_id).reverse.each do |source| %>
        <p><%= link_to source.story_comment, line_story_path(story.line.id, source.id) %></p>
      <% end %>
    <% else %>
      <p><%= link_to story.line.content, line_path(story.line_id) %></p>
        <%#= link_to @story.parent_story(@story.story_id).story_comment, line_story_path(@line.id, @story.parent_story(@story.story_id).id) %>
    <% end %>
</div>

app/views/stories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model:@story, url:line_story_path(@story.line.id, @story.id), method: :patch, local:true do |f| %>
        <div class="field">
          <%= f.label :story_comment %>
          <%= f.text_area :story_comment, autofocus:true, autocomplete:"story_comment", class:"form-control"%>
        </div>

        <div class="action">
          <%= f.submit "update story", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 my-3">
    <!--今までの投稿がうまくいかなかったらこっちを使う-->
    <h5>これまでの話</h5>
    <%#= render "stories/until_story", story:@story%>
        <% if @story.story_id.present? %>
        <div class="card col-8">
          <div class="card-body">
          <p class="card-text"><%= link_to @story.line.content, line_path(@story.line_id) %></p>
          </div>
        </div>
          <% @story.all_parents(@story.story_id).reverse.each do |source| %>
            <div class="card col-8">
              <div class="card-body">
                <p class="card-text"><%= link_to source.story_comment, line_story_path(@line.id, source.id) %></p>
              </div>
            </div>
          <% end %>
        <% else %>
        <div class="card col-8">
          <div class="card-body">
            <p class="card-text"><%= link_to @story.line.content, line_path(@story.line_id) %></p>
            <%#= link_to @story.parent_story(@story.story_id).story_comment, line_story_path(@line.id, @story.parent_story(@story.story_id).id) %>
          </div>
        </div>
        <% end %>

    <h1>story show</h1>

    <div class="card">
      <div class="card-body">
        <p class="card-text"><%= @story.story_comment %></p>
        <i class="card-text"><%= @story.user.name %></i>
        <a class="card-text">
          <% if @story.user_id == current_user.id %>
            <%= link_to "Edit", edit_line_story_path(@line.id, @story.id) %>
          <% end %>
        </a>
      </div>
    </div>

    <%= render "layouts/error", obj:@new_story %>

    <%=form_with model: @new_story, url:line_stories_path(@story.line.id), method: :post,local:true do |f| %>
      <%= f.hidden_field :story_id, value: @story.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="field">
        <%= f.label :story_comment %>
        <%= f.text_area :story_comment, autofocus:true, autocomplete: "story_comment", class:"form-control"%>
      </div>

      <div class="action">
        <%= f.submit "create story", class:"btn btn-success"%>
      </div>
   <% end %>

  <div class="col-md-12 mx-auto">
    <h3>この話の続きのstory一覧</h3>
      <div class="row">
        <% @stories.each do |story| %>
          <div class="card col-6">
            <div class="card-body">
            <p class="card-text"><%= link_to story.story_comment, line_story_path(@line.id, story.id) %></p>
            <p class="card-text"><%= story.user.name %></p>
          </div>
        <% end %>
      </div>
  </div>

  <div class="col-md-4 offset-md-1 my-5">
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

<%= form_with model:@user, url: user_path, method: :patch, local:true do |f| %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name, autofocus:true %>
</div>

<div class="field">
  <%= f.label :introduction %><br />
  <%= f.text_field :introduction, autofocus:true, autocomplete: "introduction" %>
</div>

<div class="action">
  <%= f.submit "update" %>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <h1><%= @user.name %>さんの詳細ページ</h1>
      <p><%= @user.introduction %></p>
      <p>
        <%= link_to edit_user_path(@user.id) do %>
          <i class="fas fa-user-cog"></i> Edit
        <% end %>
      </p>
    </div>

    <div class="col-md-5">
      <h3><%=@user.name%>さん作の書き出し文一覧</h3>
        <% @lines.each do |line| %>
          <div class="card">
            <div class="card-body">
              <p class="card-text"><%= link_to line.content, line_path(line.id) %></p>
              <p class="card-text"><%= line.book_title %></p>
            </div>
          </div>
        <% end %>
    </div>

    <div class="col-md-5 offset-md-2">
      <h3><%=@user.name%>さん作のStory一覧</h3>
        <% @user.stories.all.each do |story| %>
          <div class="card">
            <div class="card-body">
              <p class="card-text"><%= link_to story.story_comment, line_story_path(story.line.id, story.id)%></p>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>